---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible
  - name: centos8
    image: geerlingguy/docker-centos8-ansible
  - name: sles15
    image: opensuse/leap:latest
provisioner:
  name: ansible
verifier:
  name: ansible
