---
galaxy_info:
  author: Rudder
  description: Ansible role to manage your rudder repository (for subscriptors)
  company: Rudder
  license: GPLv3
  min_ansible_version: 2.9
  role_name: rudder_repository
  namespace: rudder

  galaxy_tags:
  - rudder
  - automation
  - compliance
  - audit

  platforms:
    - name: Ubuntu
      versions:
        - all

    - name: Debian
      versions:
        - all

    - name: SLES
      versions:
         - all

    - name: EL
      versions:
        - all

dependencies: []
