---
galaxy_info:
  author: Rudder
  description: Ansible role to manage your rudder repository (for subscriptors)
  company: Rudder
  license: GPLv3
  min_ansible_version: 2.9
  role_name: rudder_repository
  namespace: rudder

  galaxy_tags:
  - rudder
  - automation
  - compliance
  - audit

  platforms:
    - name: Ubuntu
      versions:
        - 10.04-LTS
        - 12.04-LTS
        - 14.04-LTS
        - 16.04-LTS
        - 18.04-LTS
        - 20.04-LTS

    - name: Debian
      versions:
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11

    - name: SLES
      versions:
         - 10-SP3
         - 11

    - name: RHEL
      versions:
         - 3
         - 5
         - 6
         - 7
         - 8

dependencies: []
