---
- name: Print key
  debug:
    msg: "{{ rudder_apt_key_url }}"
- name: Adding Rudder Repo Key
  apt_key:
    url: "{{ rudder_apt_key_url }}"
    state: present
  become: true

- name: Adding Rudder Repo
  apt_repository:
    repo: "deb {{ repository_url }}/apt/{{ rudder_version|string }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: "{{ update_cache }}"
    validate_certs: yes
  become: true
