---
- name: Print key
  debug:
    msg: "{{ rudder_apt_key_url }}"
- name: Adding Rudder Repo Key
  apt_key:
    url: "{{ rudder_apt_key_url }}"
    state: present
  become: true
  when: rudder_apt_key_url|length > 0

- name: Adding Rudder Repo
  apt_repository:
    repo: "deb {{ repository_url }}/apt/{{ rudder_version|string }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: "{{ rudder_update_cache }}"
    validate_certs: yes
  when: repository_url|length == 0
  become: true

- name: Adding Rudder Repo (from repository_url parameter)
  apt_repository:
    repo: "deb {{ repository_url }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: "{{ rudder_update_cache }}"
    validate_certs: yes
  when: repository_url|length > 0
  become: true
