- name: Adding Rudder Repo Key
  rpm_key:
    key: "{{ rpm_key_url }}"
    state: present
  become: true
  when: rpm_key_url|length > 0

- name: Compute Rudder repo
  ansible.builtin.set_fact:
    repository_url: "{{ rudder_repository_repo_url }}/rpm/{{ rudder_version|string }}/RHEL_{{ ansible_distribution_major_version }}/"
  when: repository_url|length == 0

- name: Print repo
  debug:
    msg: "{{ repository_url }}"

- name: Adding Rudder Repo
  yum_repository:
    name: Rudder
    description: Rudder
    state: present
    baseurl: "{{ repository_url }}"
    enabled: yes
    gpgcheck: true
    sslverify: yes
  become: true
