- name: Adding Rudder Repo Key
  rpm_key:
    key: "{{ rpm_key_url }}"
    state: present
  when: rpm_key_url|length > 0

- name: Compute Rudder repo
  ansible.builtin.set_fact:
    repository_url: "{{ rudder_repository_repo_url }}/rpm/{{ rudder_version|string }}/SLES_{{ ansible_distribution_major_version }}/"
  when: repository_url|length == 0

- name: Adding Rudder Repo
  zypper_repository:
    name: Rudder
    description: Rudder
    state: present
    repo: "{{ repository_url }}"
    enabled: yes
    runrefresh: "{{ rudder_update_cache }}"

- name: Ensure repository username
  community.general.ini_file:
    path: /root/.zypp/credentials.cat
    section: "{{ repository_url }}"
    option: "username"
    value: "{{ repository_username }}"
  when: repository_username | length > 0

- name: Ensure repository password
  community.general.ini_file:
    path: /root/.zypp/credentials.cat
    section: "{{ repository_url }}"
    option: "password"
    value: "{{ repository_password }}"
  when: repository_username | length > 0
