- name: Define repository url with creds
  set_fact:
    rudder_repository_repo_url: "https://{{ repository_username }}:{{ repository_password }}@{{ repository }}"
  when: (repository_username | length > 0)

- name: Define repository url without creds
  set_fact:
    rudder_repository_repo_url: "https://{{ repository }}"
  when: repository_username | length == 0
