---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
    - name: ubuntu2004
      image: geerlingguy/docker-ubuntu2004-ansible:latest
    - name: centos8
      image: geerlingguy/docker-centos8-ansible:latest
  # Requires a non priviliged systemd sles15 docker image
  #- name: sles15
  #  image: opensuse/leap:latest
  #  command: /sbin/init
  #  tmpfs:
  #    - /run
  #    - /tmp
  #  volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible

verifier:
  name: ansible
