- include_tasks: sles.yml
  when: ansible_os_family == "Suse"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux" and ansible_distribution != "Fedora"

- include_tasks: configure.yml
