---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Get rudder cli path
      command: which rudder
      register: rudder_path

    - name: Get rudder policy server
      command: cat /var/rudder/cfengine-community/policy_server.dat
      register: current_policy_server

    - name: Rudder-agent must be installed
      assert:
        that:
          - rudder_path.stdout == "/usr/bin/rudder"

    - name: Policy server must be configured
      assert:
        that:
          - current_policy_server.stdout == "rudder.server"

    - include_tasks: redhat.yml
      when: ansible_os_family == "RedHat"
    - include_tasks: debian.yml
      when: ansible_os_family == "Debian"
    - include_tasks: sles.yml
      when: ansible_os_family == "Suse"
