dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-centos8-ansible
    pre_build_image: true
    command: "yum update --disablerepo=appstream"
provisioner:
  name: ansible
verifier:
  name: ansible
